# Generated by Django 5.0.4 on 2024-04-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_alter_purchaseorder_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='on_time',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
